import os
ans = input("WARNING! what you do with your devices and this script is your responsibility, i will not be held accountable if you break your phone, void your warranty etc.. THIS IS YOUR RESPONSIBILITY! If you agree to these terms, please type EXACTLY LIKE SHOWN : Yes i understand ")
if ans == 'Yes i understand' :
    print("Alright! lets start")
else :
    quit()
ans = input("Do you wish to clean the 'dirt programs? (built in ads, apps hidden from users etc..) y/n : ")
if ans == 'y':
    os.system("adb uninstall com.google.android.adservices.api")
    os.system("adb uninstall com.miui.analytics")
    os.system("adb uninstall com.google.android.marvin.talkback")
    os.system("adb uninstall com.google.android.projection.gearhead")
    os.system("adb uninstall com.android.egg")
    os.system("adb uninstall com.google.android.apps.restore")
    os.system("adb uninstall com.google.android.as")
    os.system("adb uninstall android.qvaoverlay.common")
    os.system("adb uninstall com.mi.globalminusscreen")
    os.system("adb uninstall com.longcheertel.AutoTest")
    os.system("adb uninstall com.miui.backup")
    os.system("adb uninstall com.android.bluetoothmidiservice")
    os.system("adb uninstall com.miui.extraphoto")
    os.system("adb uninstall com.xiaomi.barrage")
    os.system("adb uninstall com.xiaomi.calendar")
    os.system("adb uninstall com.android.calllogbackup")
    os.system("adb uninstall com.android.cameraextensions")
    os.system("adb uninstall com.longcheertel.cit")
    os.system("adb uninstall com.miui.cleaner")
    os.system("adb uninstall com.miui.cloudbackup")
    os.system("adb uninstall com.android.cellbroadcastreceiver.overlay.common")
    os.system("adb uninstall com.android.inputsettings.overlay.miui")
    os.system("adb uninstall com.android.managedprovisioning.overlay")
    os.system("adb uninstall com.android.overlay.gmscontactprovider")
    os.system("adb uninstall com.android.overlay.gmssettingprovider")
    os.system("adb uninstall com.android.overlay.gmssettings")
    os.system("adb uninstall com.android.overlay.gmstelecomm")
    os.system("adb uninstall com.android.overlay.gmstelephony")
    os.system("adb uninstall com.android.providers.partnerbookmarks")
    os.system("adb uninstall com.android.settings.overlay.miui")
    os.system("adb uninstall com.android.stk.overlay.miui")
    os.system("adb uninstall com.android.systemui.accessibility.accessibilitymenu")
    os.system("adb uninstall com.android.systemui.overlay.common")
    os.system("adb uninstall com.android.systemui.overlay.miui")
    os.system("adb uninstall com.android.virtualmachine.res")
    os.system("adb uninstall com.google.android.cellbroadcastreceiver.overlay.miui")
    os.system("adb uninstall com.google.android.cellbroadcastrservice.overlay.miui")
    os.system("adb uninstall com.google.android.federatedcompute")
    os.system("adb uninstall com.google.android.overlay.gmsconfig.asi")
    os.system("adb uninstall com.google.android.overlay.healthconnect")
    os.system("adb uninstall com.google.android.overlay.modules.captiveportallogin.forframework")
    os.system("adb uninstall com.google.android.overlay.modules.documentsui")
    os.system("adb uninstall com.google.android.overlay.modules.permissioncontroller")
    os.system("adb uninstall com.miui.miwallpaper.overlay")
    os.system("adb uninstall com.miui.miwallpaper.overlay")
    os.system("adb uninstall com.miui.miwallpaper.overlay.customize")
    os.system("adb uninstall com.miui.phone.carriers.overlay.h3g")
    os.system("adb uninstall com.miui.phone.carriers.overlay.vodafone")
    os.system("adb uninstall com.miui.qr")
    os.system("adb uninstall com.miui.settings.rro.deivce.hide.statusbar.overlay")
    os.system("adb uninstall com.miui.settings.rro.devjice.type.overlay")
    os.system("adb uninstall com.miui.system.overlay")
    os.system("adb uninstall com.miui.wallpaper.overlay")
    os.system("adb uninstall com.miui.wallpaper.overlay")
    os.system("adb uninstall com.miui.wallpaper.overlay.customize")
    os.system("adb uninstall com.qti.service.colorservice")
    os.system("adb uninstall com.qualcomm.atfwd2")
    os.system("adb uninstall com.qualcomm.qti.devicestatisticsservice")
    os.system("adb uninstall com.qualcomm.qti.qms.service.trustzoneaccess")
    os.system("adb uninstall com.qualcomm.qti.uim")
    os.system("adb uninstall com.qualcomm.qti.uimGbaApp")
    os.system("adb uninstall com.qualcomm.uimremoteclient")
    os.system("adb uninstall com.qualcomm.uimremoteserver")
    os.system("adb uninstall com.google.ambient.streaming")
    os.system("adb uninstall com.google.android.apps.restore")
    os.system("adb uninstall com.qti.dcf")
    os.system("adb uninstall com.google.android.apps.turbo")
    os.system("adb uninstall com.qti.qualcomm.deviceinfo")
    os.system("adb uninstall com.google.android.gms.supervision")
    os.system("adb uninstall com.goodix.gftest")
    os.system("adb uninstall com.google.android.gms.location.history")
    os.system("adb uninstall com.xiaomi.glgm")
    os.system("adb uninstall com.google.android.apps.healthdata")
    os.system("adb uninstall com.qualcomm.location")
    os.system("adb uninstall com.google.mainline.adservices")
    os.system("adb uninstall com.google.android.feedback")
    os.system("adb uninstall com.facebook.system")
    os.system("adb uninstall com.facebook.services")
    os.system("adb uninstall com.xiaomi.payment")
    os.system("adb uninstall com.miui.videoplayer")
    os.system("adb uninstall com.xiaomi.trustservice")
    os.system("adb uninstall com.miui.msa.global")
    os.system("adb uninstall com.qualcomm.qti.performancemode")
    os.system("adb uninstall com.qualcomm.qti.server.qtiwifi")
    os.system("adb uninstall com.qualcomm.qti.ridemodeaudio")
    os.system("adb uninstall com.xiaomi.mtb")
    os.system("adb uninstall com.fingerprints.sensortesttool")
    print("The picomi program has cleared the 'dirt' apps")
ans = input("Do you wish to uninstall the unneccesary apps? (music, google tv, facebook) a.k.a. starting from a semi clean slate, this will not delete your images or format anything. y/n : ")
if ans == 'y':
    os.system("adb uninstall com.google.android.apps.youtube.music")
    os.system("adb uninstall com.miui.player")
    os.system("adb uninstall com.miui.micloudsync")
    os.system("adb uninstall com.mi.globalbrowser")
    os.system("adb uninstall com.facebook.appmanager")
    os.system("adb uninstall com.google.android.apps.tachyon")
    os.system("adb uninstall com.google.android.feedback")
    os.system("adb uninstall com.google.android.videos")
    os.system("adb uninstall com.google.android.onetimeinitializer")
    os.system("adb uninstall com.google.android.apps.subscriptions.red")
    os.system("adb uninstall com.xiaomi.mipicks")
    os.system("adb uninstall com.miui.phrase")
    os.system("adb uninstall com.miui.fmservice")
    os.system("adb uninstall com.miui.fm")
    os.system("adb uninstall com.miui.bugreport")
    print("The picomi program has cleared the unneccesary apps")
print("Bye!")